apiVersion: v1
kind: Service
metadata:
  name: cervejas-service
  namespace: cervejaria
spec:
  selector:
    app: cervejas-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
  type: NodePort
  