apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerveja-pvc
  namespace: cervejaria
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cervejas