apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: cervejaria
spec:
  selector:
    app: db-acme
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  